name: publish

on:
  push:
    branches:
      - trunk # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.123.8"
          extended: true

      - name: Install requirements
        run: |
          npm install

      - name: Build
        run: hugo --minify

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/trunk' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: blog.spiceai.org
